### ISSUE TITLE
Missing channel<>interface documentation

### ISSUE THREAD

**Issue by JoannaAtZipline** [slimelec/ollie-hw#10]
When plugged into a host, the ollie presents as either 4 com ports in windows or four `/dev/ttyUSB` devices in linux. It is unclear which USB device corresponds to which interface (IE: channel A / `tty/usb0` -> UART A, channelC -> RS485). It would be so very helpful for information about matching channel to interface

**Comment by meatpiHQ** [comment]
@JoannaAtZipline please refer to the [Pinout ](https://github.com/slimelec/ollie-hw#pinout). On Linux I suggest you install the drivers, and the interface will show up as /dev/ttyXRUSB[0-3]

UARTA/ttyXRUSB0 and UARTB/ttyXRUSB1 are ttl level 
UARTC/ttyXRUSB2 is RS485
UARTD/ttyXRUSB3 is RS232
