### ISSUE TITLE
Usb Type C port

### ISSUE THREAD

**Issue by chunkycarrie** [slimelec/ollie-hw#2]
Why don't You use a USB Type C port instead of micro USB?

**Comment by slimelec** [comment]
@chunkycarrie i feel like USB micro is still commonly used for this kind of tools, I know everyone is slowly moving to USB C. The Micro are still reliable and very cheap.

**Comment by chunkycarrie** [comment]
Ok, thanks for the answer. What about rs-485-4w, I meet them often at building automation systems, are you planning to implement it or You just want to cover more common 2wire standard?
Are you planning to project some secured enclosure (some type of dust resistance etc) so it can be used in a field conditions?

**Comment by slimelec** [comment]
@chunkycarrie Sorry for the late reply! 

At the moment there is no plan to modify the design to add support for rs485-4w. But It's something to consider.

As for the enclosure, I will release the drawing in case anyone would like to make their own enclosure. I also have a 3d drawing for an enclosure I was working last year, I might make that public - However this enclosure was never prototyped, and I don't have much experience with 3d design so I don't know it will come out.

**Comment by slimelec** [comment]
Closing this issue if you have more questions feel free to reopen.
