### ISSUE TITLE
[Question] Compatibility with DSD TECH SH-U11

### ISSUE THREAD

**Issue by manchoz** [slimelec/ollie-hw#4]
Hi,
I'm trying to get the Ollie to communicate back-to-back with the [DSD Tech SH-U11](http://www.dsdtech-global.com/2017/04/SH-U11.html) Adapter via RS4585 to test a few Modbus stuff.

I'm able to read data into the Ollie but I'm not able to send data from the Ollie to the SH-U11. I can see data transit on the bus (using a Saleae Logic Analyzer) from the SH-U11 to the Ollie but never in the reverse.

Do you have any clue or recommendation about termination and bias setup?

Thanks!

**Comment by slimelec** [comment]
Hey @manchoz are you testing on Linux? And do you have the GND pin connected?

**Comment by manchoz** [comment]
Testing on MacOS. I can give a spin to an Ubuntu VM, also. I will let you know.

GND pin connected. 

Should the voltage selection reflects on the voltage levels on the A/B pins?

What bugs me is that I can't see nothing coming out from the Ollie with the logic analyser connected to the bus.

**Comment by slimelec** [comment]
@manchoz voltage selection is not related to RS485, voltage selection is for UART port A and B.

Have you installed the Mac [drives](https://www.maxlinear.com/support/design-tools/software-drivers)?

 It would be great if you can test with Ubuntu. Make sure to install the [drivers](https://github.com/slimelec/ollie-hw#linux) if you don't see /dev/ttyXRUSB[0-3], please follow the readme instructions.

**Comment by manchoz** [comment]
Is there any "reference" distro or OS?

**Comment by slimelec** [comment]
@manchoz it should work with any distro, I've tested with Ubuntu 18.04 before.

**Comment by manchoz** [comment]
I got it working only using PuTTy for Linux as the serial emulator. What other terminal emulators have been tested?

PuTTy on Windows does not work, too.

I would like to test a few Modbus implementation ([pymodbus](https://github.com/riptideio/pymodbus)) in a client/server scenario: what is the recommended setup?

**Comment by slimelec** [comment]
@manchoz I've tried "realTerm" and "Tera Term" on windows and "screen" on Linux.

I don't see a reason why it wouldn't work with PuTTy. I'll have to try this.

As for pymodbus I think you need to set it up as serial client/server.

**Comment by manchoz** [comment]
What adapter are you trying with, besides the Ollie?

I made a few other tests and I can't get it working in TX in any other condition.

**Comment by slimelec** [comment]
@manchoz I'm testing with [DTech](https://www.dtechelectronics.com/dtech-dt-5019-usb-to-rs485-422-cable_p118.html) cable, I don't think it should matter which adapter you're using.

BTW I've just tested with PuTTy on windows just now and it works fine.

On windows do you see the XR21V1414 recognized in the device manager?

![image](https://user-images.githubusercontent.com/12411993/122565017-59c34b00-d089-11eb-826e-a8e296a47eb6.png)
